# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Dev_Build
    displayName: "Dev Build"
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget'
  
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: 'Build Project'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PowerShell@2
      displayName: 'Run Powershell Script(If Any)'
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\test.ps1
        failOnStderr: true
        errorActionPreference: stop
        showWarnings: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'CodeArtifact'

- stage: Deployment
  displayName: "Deploy App in IIS"
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - deployment: IIS_Deployment
    environment: 'Dev Environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'EnterpriseCost'
              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true