trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Code_Build
    displayName: "Code Build"
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget'
  
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: 'Build Project'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PowerShell@2
      displayName: 'Run Powershell Script(If Any)'
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\test.ps1
        failOnStderr: true
        errorActionPreference: stop
        showWarnings: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'CodeArtifact'

- stage: Deployment
  displayName: "Deployment"
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - deployment: IIS_Deployment
    environment: 'Dev Environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadBuildArtifacts@0
            displayName: "Downloading Artifacts"
            inputs:
              artifactName: 'CodeArtifact'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Setup IIS'
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'CostAutomationApp'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'AppPool'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
              Bindings:
              ParentWebsiteNameForVD: CostAutomationApp
              VirtualPathForVD: '%SystemDrive%\inetpub\wwwroot\CostAutomationApp'
              AppPoolName: AppPool
              ParentWebsiteNameForApplication: CostAutomationApp
              VirtualPathForApplication: '%SystemDrive%\inetpub\wwwroot\CostAutomationApp'
              AppPoolNameForApplication: AppPool
              
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy App on IIS'
            inputs:
              WebSiteName: 'CostAutomationApp'
              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true
          
          - task: PowerShell@2
            displayName: 'Remove Cache'
            inputs:
              targetType: 'inline'
              script: |
                Set-WebConfigurationProperty -pspath MACHINE/WEBROOT/APPHOST/CostAutomationApp `
                    -filter "system.webServer/staticContent/clientCache" `
                    -name "cacheControlMode" -value "UseMaxAge"

                Set-WebConfigurationProperty -pspath MACHINE/WEBROOT/APPHOST/CostAutomationApp `
                    -filter "system.webServer/staticContent/clientCache" `
                    -name "cacheControlMaxAge" -value "00:00:00"

          